app.config(function($stateProvider, $urlRouterProvider){
    $urlRouterProvider.otherwise('/login');
    $stateProvider
        .state('login',{
            url:'/login',
            controller:'loginCtrl',
            templateUrl:'views/login.html'
        })
        .state('commonLayout.logout',{
            controller:'logoutCtrl'
        })
        .state('registration',{
            url:'/registration',
            controller:'registrationFormCtrl',
            templateUrl:'views/registrationForm.html'
        })
        .state('changePassword',{
            url:'/changePassword',
            controller:'changePasswordCtrl',
            templateUrl:'views/changePassword.html'
        })
        .state('buyerLayout',{
            url:'/buyerLayout',
            controller:'buyerLayoutCtrl',
            templateUrl:'views/buyerLayout.html'
        })
        .state('buyerLayout.dashBoardMenu',{
            url:'/dashBoardMenu',
            controller:'dashBoardMenuCtrl',
            templateUrl:'views/dashBoardMenu.html'
        })
        .state('buyerLayout.buyerRequests',{
            url:'/buyerRequests',
            controller:'showBuyerRequestsToFarmerCtrl',
            templateUrl:'views/buyerRequests.html'
        })
        .state('buyerLayout.myFarmerRequests',{
            url:'/myFarmerRequests',
            controller:'myFarmerRequestCtrl',
            templateUrl:'views/myFarmerRequests.html'
        })

        .state('farmerLayout',{
            url:'/farmerLayout',
            controller:'farmerLayoutCtrl',
            templateUrl:'views/farmerLayout.html'
        })
        .state('farmerLayout.farmerHome',{
            url:'/farmerHome',
            controller:'farmerHomeCtrl',
            templateUrl:'views/farmerHome.html'
        })

        .state('adminLayout',{
            url:'/adminLayout',
            controller:'adminLayoutCtrl',
            templateUrl:'views/adminLayout.html'
        })
        /*.state('commonLayout.dashBoardMenu.episodeOne',{
            url:'/episodeOne',
            controller:'episodeOneCtrl',
            templateUrl:'views/episodeOne.html'
        })
        .state('viewTwo',{
            url:'/viewTwo',
            controller:'viewTwoCtrl',
            templateUrl:'views/viewTwo.html'
        })*/
        .state('buyerLayout.dashBoard',{
            url:'/dashBoard',
            controller:'dashBoardCtrl',
            templateUrl:'views/dashBoard.html'
        })
        /*.state('commonLayout.playScreen',{
            url:'/playScreen',
            controller:'playScreenCtrl',
            templateUrl:'views/playScreen.html'
        })
        .state('commonLayout.episodeOneSummary',{
            url:'/episodeOneSummary',
            controller:'episodeOneSummaryCtrl',
            templateUrl:'views/episodeOneSummary.html'
        })
        .state('commonLayout.episodeTwo',{
            url:'/episodeTwo',
            controller:'episodeTwoCtrl',
            templateUrl:'views/episodeTwo/episodeTwo.html'
        })
        .state('commonLayout.dashBoardMenu.feedbackForm',{
            url:'/feedbackForm',
            controller:'feedbackFormCtrl',
            templateUrl:'views/feedbackForm.html'
        })
        .state('commonLayout.episodeThree',{
            url:'/episodeThree',
            controller:'episodeThreeCtrl',
            templateUrl:'views/episodeThree/episodeThree.html'
        })
        .state('commonLayout.episodeFour',{
            url:'/episodeFour',
            controller:'episodeFourCtrl',
            templateUrl:'views/episodeFour/episodeFour.html'
        })
        .state('commonLayout.episodeFive',{
            url:'/episodeFive',
            controller:'episodeFiveCtrl',
            templateUrl:'views/episodeFive/episodeFive.html'
        })*/
});